# Generated by Django 4.2.26 on 2025-11-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cachorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('idade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
