# Generated by Django 4.2.26 on 2025-11-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='idade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
