# Generated by Django 4.2.26 on 2025-11-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_alter_cachorro_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='foto',
            field=models.ImageField(null=True, upload_to='ftsAnimais/'),
        ),
    ]
