# Generated by Django 4.2.26 on 2025-11-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_cachorro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ftsAnimais/'),
        ),
    ]
