# Generated by Django 4.2.26 on 2025-11-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0004_alter_cachorro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
