# Generated by Django 4.2.26 on 2025-11-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0005_alter_cachorro_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='adotado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='arrecadado',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='meta',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10000),
        ),
    ]
