# Generated by Django 4.2.26 on 2025-11-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0006_cachorro_adotado_cachorro_arrecadado_cachorro_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='arrecadado',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='meta',
            field=models.FloatField(default=0.0),
        ),
    ]
