# Generated by Django 4.2.26 on 2025-11-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0007_alter_cachorro_arrecadado_alter_cachorro_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='adotadoPor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='historia',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
