# Generated by Django 4.2.26 on 2025-11-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0008_cachorro_adotadopor_cachorro_historia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='diaAdocao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
