# Generated by Django 4.2.26 on 2025-11-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0009_cachorro_diaadocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='porte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
